# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f82090c9478231b61dc6a865b49b573f94baaac5a712a1e495c1d67cb07a890860e99b91ff5e7e711c7cb36bd540b265bd83825adde5924b62ab2e4afe9caec

test:
  secret_key_base: b84bfcae625b7ba8ef1f0e38e46abf641ecb26d012b088ea31d936c0f13a8a688cb22324df608034da9af9a914fbec5448f69837268d51eb4f7b8876a7f98972

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
